CREATE DATABASE Odontologia;
USE Odontologia;

CREATE TABLE Paciente(
    ID_PACIENTE INT, 
    PRI_NOMBRE TEXT NOT NULL,
    SEG_NOMBRE TEXT NOT NULL,
    PRI_APELLIDO TEXT NOT NULL,
    SEG_APELLIDO TEXT NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    CORREO TEXT NOT NULL,
    DIRECCION TEXT NOT NULL,
    FECHA_NAC DATE NOT NULL,

    CONSTRAINT PK_ID_PACIENTE PRIMARY KEY (ID_PACIENTE)
);

CREATE TABLE SUCURSAL(
    ID_SUCURSAL INT,
    DIRECCION VARCHAR(50) NOT NULL,
    AVENIDA VARCHAR(30) NOT NULL,
    CALLE VARCHAR(30) NOT NULL,
    CIUDAD VARCHAR(10) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,

    CONSTRAINT PK_ID_SUCURSAL PRIMARY KEY (ID_SUCURSAL)
);

CREATE TABLE EMPLEADO(
    DNI_EMPLEADO INT,
    ID_PACIENTE INT, 
    PRI_NOMBRE TEXT NOT NULL,
    SEG_NOMBRE TEXT NOT NULL,
    PRI_APELLIDO TEXT NOT NULL,
    SEG_APELLIDO TEXT NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    CARGO ENUM ('Recepcionista','Contador','Gerente Administrativo') NOT NULL, /*Pueden haber mas tipos de cargo, los que estan ahi solo son de ejemplo*/
    SEXO ENUM ('Femenino','Masculino') NOT NULL,
    ID_SUCURSAL INT NOT NULL,

    CONSTRAINT PK_DNI_EMPLEADO PRIMARY KEY (DNI_EMPLEADO),
    CONSTRAINT FK_ID_SUCURSAL_E FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE CONSULTORIO(
    NUM_CONSULTORIO INT,
    ID_SUCURSAL INT,
    NOMBRE_CONSULTORIO VARCHAR (12) NOT NULL, 
    UBICACION VARCHAR(10) NOT NULL,

    CONSTRAINT PK_NUM_CONSULTORIO PRIMARY KEY (NUM_CONSULTORIO),
    CONSTRAINT PK_ID_SUCURSAL_C PRIMARY KEY (ID_SUCURSAL),
    CONSTRAINT FK_ID_SUCURSAL_C FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE ODONTOLOGO(
    ID_ODONTOLOGO INT,
    ESPECIALIDAD VARCHAR(20) NOT NULL,
    PRI_NOMBRE TEXT NOT NULL,
    SEG_NOMBRE TEXT NOT NULL,
    PRI_APELLIDO TEXT NOT NULL,
    SEG_APELLIDO TEXT NOT NULL,
    ID_SUCURSAL INT NOT NULL,

    CONSTRAINT PK_ID_ODONTOLOGO PRIMARY KEY (ID_ODONTOLOGO),
    CONSTRAINT FK_ID_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL)
);

CREATE TABLE CONSULTA(
    NUM_CONSULTA INT,
    FECHA DATE NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_ODONTOLOGO INT NOT NULL,

    CONSTRAINT PK_NUM_CONSULTA PRIMARY KEY (NUM_CONSULTA),
    CONSTRAINT FK_ID_PACIENTE_CON FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_ID_ODONTOLOGO_RE FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGO(ID_ODONTOLOGO)

);

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT,
    DESCRIPCION TEXT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_ODONTOLOGO INT NOT NULL,

    CONSTRAINT PK_ID_EXPEDIENTE PRIMARY KEY (ID_EXPEDIENTE),
    CONSTRAINT FK_ID_PACIENTE_EX FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_ID_ODONTOLOGO_RE FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGO(ID_ODONTOLOGO)
);

CREATE TABLE RECETA_MEDICA(
    ID_RECETA INT,
    DESCRIPCION TEXT NOT NULL,
    FECHA_ACTUAL DATE NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_ODONTOLOGO INT NOT NULL,

    CONSTRAINT PK_ID_RECETA PRIMARY KEY (ID_RECETA),
    CONSTRAINT FK_ID_PACIENTE_RE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_ID_ODONTOLOGO_RE FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGO(ID_ODONTOLOGO)
);

CREATE TABLE TRATAMIENTO(
    ID_TRATAMIENTO INT,
    NOMBRE VARCHAR(30) NOT NULL,
    PRECIO FLOAT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    ID_ODONTOLOGO INT NOT NULL,

    CONSTRAINT PK_ID_TRATAMIENTO PRIMARY KEY (ID_TRATAMIENTO),
    CONSTRAINT FK_ID_ODONTOLOGO_RE FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGO(ID_ODONTOLOGO)
);

CREATE TABLE FACTURA(
    NUM_FACTURA INT,
    DESCRIPCION VARCHAR(50) NOT NULL,
    TOTAL_PAGAR FLOAT NOT NULL,
    DIRECCION TEXT NOT NULL,
    FECHA_ACTUAL DATE NOT NULL,
    SUBTOTAL FLOAT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_ODONTOLOGO INT NOT NULL,

    CONSTRAINT NUM_FACTURA PRIMARY KEY (NUM_FACTURA),
    CONSTRAINT FK_ID_PACIENTE_RE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_ID_ODONTOLOGO_RE FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGO(ID_ODONTOLOGO)
);
